name: Unzip SecureAuraZip

on:
  push:
    branches:
      - main   # Run when you push to main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install unzip utility
      - name: Install unzip
        run: sudo apt-get install unzip -y

      # Step 3: Unzip your file
      - name: Unzip SecureAuraZip.zip
        run: unzip SecureAuraZip.zip -d ./unzipped

      # Step 4: Commit unzipped files back to repo
      - name: Commit unzipped files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./unzipped
          git commit -m "Unzipped SecureAuraZip.zip"
          git push
